services:
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - 5432:5432
    volumes:
      - ./.containers/postgresql/data:/var/lib/postgresql/data
  rabbitmq:
    image: rabbitmq:4.1.0-management
    volumes:
      - ./.containers/rabbitmq:/var/lib/rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
