@PreciosGamer.Products.API_HostAddress = http://localhost:5153

GET {{PreciosGamer.Products.API_HostAddress}}?p=0&s=10
Accept: application/json

###

GET {{PreciosGamer.Products.API_HostAddress}}/1/100-100000593WOF
Accept: application/json

###

GET {{PreciosGamer.Products.API_HostAddress}}/1/100-100000593WOF/prices?startDate=4/30/2025&endDate=5/4/2025
Accept: application/json